- name: images | update template list
  command: pveam update

- name: images | download debian template
  shell: >
    pveam download {{ pve_storage|default('local') }} {{ item }}
  with_items: "{{ pve_templates_list | default([]) }}"

- name: images | download opnsense iso
  shell: |
    wget -P /var/lib/vz/template/iso "{{ item }}"
    bunzip2 /var/lib/vz/template/iso/*.bz2 > /dev/null
  with_items: "{{ iso_list | default([]) }}"
